/** @type {import('tailwindcss').Config} */

const semanticColor = (tokenName) => `rgb(var(--color-${tokenName}) / <alpha-value>)`;

module.exports = {
  darkMode: "class",
  content: [
    "./cloud_resume/templates/**/*.html",
    "./cloud_resume/**/*.py",
  ],
  theme: {
    extend: {
      colors: {
        background: semanticColor("background"),
        "on-background": semanticColor("on-background"),
        surface: semanticColor("surface"),
        "on-surface": semanticColor("on-surface"),
        "on-surface-variant": semanticColor("on-surface-variant"),
        "surface-dim": semanticColor("surface-dim"),
        "surface-bright": semanticColor("surface-bright"),
        "surface-container-lowest": semanticColor("surface-container-lowest"),
        "surface-container-low": semanticColor("surface-container-low"),
        "surface-container": semanticColor("surface-container"),
        "surface-container-high": semanticColor("surface-container-high"),
        "surface-container-highest": semanticColor("surface-container-highest"),
        "surface-variant": semanticColor("surface-variant"),
        "surface-tint": semanticColor("surface-tint"),
        primary: semanticColor("primary"),
        "on-primary": semanticColor("on-primary"),
        "primary-container": semanticColor("primary-container"),
        "on-primary-container": semanticColor("on-primary-container"),
        "primary-fixed": semanticColor("primary-fixed"),
        "primary-fixed-dim": semanticColor("primary-fixed-dim"),
        "on-primary-fixed": semanticColor("on-primary-fixed"),
        "on-primary-fixed-variant": semanticColor("on-primary-fixed-variant"),
        secondary: semanticColor("secondary"),
        "on-secondary": semanticColor("on-secondary"),
        "secondary-container": semanticColor("secondary-container"),
        "on-secondary-container": semanticColor("on-secondary-container"),
        "secondary-fixed": semanticColor("secondary-fixed"),
        "secondary-fixed-dim": semanticColor("secondary-fixed-dim"),
        "on-secondary-fixed": semanticColor("on-secondary-fixed"),
        "on-secondary-fixed-variant": semanticColor("on-secondary-fixed-variant"),
        tertiary: semanticColor("tertiary"),
        "on-tertiary": semanticColor("on-tertiary"),
        "tertiary-container": semanticColor("tertiary-container"),
        "on-tertiary-container": semanticColor("on-tertiary-container"),
        "tertiary-fixed": semanticColor("tertiary-fixed"),
        "tertiary-fixed-dim": semanticColor("tertiary-fixed-dim"),
        "on-tertiary-fixed": semanticColor("on-tertiary-fixed"),
        "on-tertiary-fixed-variant": semanticColor("on-tertiary-fixed-variant"),
        error: semanticColor("error"),
        "on-error": semanticColor("on-error"),
        "error-container": semanticColor("error-container"),
        "on-error-container": semanticColor("on-error-container"),
        outline: semanticColor("outline"),
        "outline-variant": semanticColor("outline-variant"),
        "inverse-surface": semanticColor("inverse-surface"),
        "inverse-on-surface": semanticColor("inverse-on-surface"),
        "inverse-primary": semanticColor("inverse-primary"),
      },
      fontFamily: {
        headline: ["Space Grotesk", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
