/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./cloud_resume/templates/**/*.html",
    "./cloud_resume/**/*.py",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#585be6",
        "on-secondary-container": "#596373",
        "surface-container": "#e6eeff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "outline-variant": "#c3c6d7",
        tertiary: "#3e3fcc",
        "on-error": "#ffffff",
        "on-surface": "#121c2a",
        secondary: "#555f6f",
        "inverse-primary": "#b4c5ff",
        "surface-dim": "#d0dbed",
        "primary-container": "#2563eb",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f1eeff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d9e3f6",
        "secondary-container": "#d6e0f3",
        "on-tertiary-fixed": "#07006c",
        "on-surface-variant": "#434655",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#d9e3f6",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e1e0ff",
        outline: "#737686",
        "surface-variant": "#d9e3f6",
        "secondary-fixed-dim": "#bdc7d9",
        primary: "#004ac6",
        "surface-container-high": "#dee9fc",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#121c2a",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-tint": "#0053db",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3d4756",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#27313f",
        "on-primary-container": "#eeefff",
        "on-background": "#121c2a",
      },
      fontFamily: {
        headline: ["Space Grotesk", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
