---
- name: Install Docker dependencies
  apt:
    state: latest
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    state: latest
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - Start & enable Docker
