---
collections:
  - name: amazon.aws
    version: 8.0.0
  - name: google.cloud
    version: 1.3.0
  - name: community.docker
    version: 3.10.3
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 6.4.0