- name: Install updates and reboot if needed
  hosts: webserver
  vars:
    ansible_user: ansible
  
  tasks:
    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      become: yes
    
    - name: Check if a reboot is required
      ansible.builtin.stat: 
        path: /var/run/reboot-required 
        get_md5: no
      register: reboot_required_file

    - name: Reboot if needed
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for updates."
        reboot_timeout: 600
      when: reboot_required_file.stat.exists
      become: yes


