---
- name: Configure Cloud Resume
  hosts: webserver
  vars:
    ansible_user: ansible
    webserver_fqdn: "resume.sbrtech.xyz"
    webserver_port: 8080
    webserver_image: ghcr.io/sbrupert/cloud-resume
    letsencrypt_staging: true

  handlers:
    - name: restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted
        become: true

  tasks:
    - name: Configure Fail2Ban
      block:
        - name: Install Fail2Ban
          ansible.builtin.apt:
            name: fail2ban
            state: present
            update_cache: true

        - name: Create Fail2Ban jail for SSH
          ansible.builtin.copy:
            dest: /etc/fail2ban/jail.local
            owner: root
            group: root
            mode: 0644
            content: |
              [sshd]
              enabled = true
              maxretry = 3
              findtime = 300
              bantime = 3600
              ignoreip = 127.0.0.1
          notify: restart fail2ban
        
        - name: Enable and start the Fail2Ban service
          ansible.builtin.service:
            name: fail2ban
            state: started
            enabled: true
      become: true
      tags: fail2ban

    - name: Install Docker
      import_role:
        name: docker
      tags: docker
      become: true

    - name: Configure Datadog
      import_role:
        name: datadog.dd.agent
      tags: datadog
      become: true

    - name: Setup Website
      block:
        - name: Start container
          community.docker.docker_container:
            name: cloud-resume
            image: "{{ webserver_image }}"
            state: started
            restart_policy: "always"
            pull: "always"
            published_ports: "8080:{{ webserver_port }}"
            labels:
              com.datadoghq.tags.env: cloud-resume-prod
              com.datadoghq.tags.service: resume-website
          tags: deploy

        - name: Configure Caddy
          import_role:
            name: caddy
          tags: caddy
          become: true
      tags: app
