#
name: Deploy with Ansible

on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT_CONTENTS:
        required: true
        description: "GCP Service Account file for ansible inventory"
      SSH_PRIVATE_KEY:
        required: true
        description: "SSH key for connecting to instances"
      VAULT_PASSWORD:
        required: true
        description: "Ansible vault key for decrypting secrets"

  workflow_dispatch:
    inputs:
      tags:
        description: 'Ansible tags to limit task execution.'
        required: false

concurrency: ansible-deploy

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required packages/modules
        run: pip install -r ./ansible/requirements.txt

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: playbook.yaml
          directory: ./ansible
          # Set connection timeout to 5 minutes to deal with shared instance slowdowns.
          configuration: |
            [defaults]
            timeout = 300
          key: "${{secrets.SSH_PRIVATE_KEY}}"
          vault_password: "${{secrets.VAULT_PASSWORD}}"
          requirements: galaxy-requirements.yaml
          options: |
            --inventory inventory.gcp.yaml ${{ github.event.inputs.tags && format('-t {}', github.event.inputs.tags) || '' }}
        env:
          GCP_SERVICE_ACCOUNT_CONTENTS: "${{secrets.GCP_SERVICE_ACCOUNT_CONTENTS}}"