#
name: Deploy with Ansible

on:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required packages/modules
        run: pip install -r ./ansible/requirements.txt

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: playbook.yaml
          directory: ./ansible
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: galaxy-requirements.yaml
          options: |
            --inventory inventory.gcp.yaml
        env:
          GCP_SERVICE_ACCOUNT_CONTENTS: ${{secrets.GCP_SERVICE_ACCOUNT_CONTENTS}}