#
name: Deploy with Ansible

on:
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      # - name: Install ansible
      #   run: pip install ansible-core

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yaml
          directory: ./ansible
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: ./ansible/galaxy-requirements.yml
          options: |
            --inventory ./ansible/inventory.gcp.yaml