name: Deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  
jobs:
  git-release:
    uses: ./.github/workflows/git-release.yml
  
  build-docker-image:
    uses: ./.github/workflows/build-container.yml
    needs: [git-release]
    with:
      IMAGE_VERSION: ${{ needs.git-release.outputs.semver }}

