name: Deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  run-code-tests:
    uses: ./.github/workflows/run-code-tests.yml

  git-release:
    needs: run-code-tests
    uses: ./.github/workflows/git-release.yml
    permissions:
      contents: write
  
  build-docker-image:
    needs: git-release
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      IMAGE_VERSION: ${{ needs.git-release.outputs.semver }}

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    secrets:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

  ansible-deploy:
    needs: [terraform-apply, git-release, build-docker-image]
    uses: ./.github/workflows/ansible-deploy.yml
    with: 
      IMAGE_VERSION: ${{ needs.git-release.outputs.semver }}
    secrets:
      GCP_SERVICE_ACCOUNT_CONTENTS: "${{secrets.GCP_SERVICE_ACCOUNT_CONTENTS}}"
      SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
      VAULT_PASSWORD: "${{secrets.VAULT_PASSWORD}}"
