name: Deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  
jobs:
  git-release:
    uses: ./.github/workflows/git-release.yml
  
  build-docker-image:
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [git-release]
    with:
      IMAGE_VERSION: ${{ needs.git-release.outputs.semver }}

