name: Deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - "main"


jobs:
  run-code-tests:
    uses: ./.github/workflows/run-code-tests.yml

  git-release:
    uses: ./.github/workflows/git-release.yml
    permissions:
      contents: write
  
  build-docker-image:
    uses: ./.github/workflows/build-container.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [git-release]
    with:
      IMAGE_VERSION: ${{ needs.git-release.outputs.semver }}

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml

  ansible-deploy:
    uses: ./.github/workflows/ansible-deploy.yml
